ENV password
ENV aws_secret_key
ENV api_key

ENV AWS_ACCESS_KEY_ID="ASIAIOSFODNN7GUTXNEL"
ENV AWS_SECRET_ACCESS_KEY="kHeUAwnSUizTWpSbyGAz4f+As5LshPIjvtpswqGb"


ENV GITHUB_TOKEN="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"


ENV GOOGLE_API_KEY="AIzaf4Six4MjGwxvkarrf1LPUaCdyNSjzsyIoRI"


ENV SLACK_BOT_TOKEN="xoxb-592666205443-2542034435697-FM7vdsq184d0G5vBNiOq8MSF8t7"


ENV STRIPE_SECRET_KEY="sk_live_kiSSAXe2IyGNvprHode7efRT"


ENV TWILIO_AUTH_TOKEN


ENV FIREBASE_API_KEY

ENV JWT_SECRET

ENV AZURE_CLIENT_SECRET


ENV DB_PASSWORD
