apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: "GOOGLE_API_KEY = AIzaf4Six4MjGwxvkarrf1LPUaCdyNSjzsyIoRI"
      image: nginx:latest
      ports:
        - containerPort: 80
